# Generated by Django 5.1.2 on 2025-11-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0002_payment_payment_type_payment_razorpay_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='days',
            new_name='validity',
        ),
    ]
