# Generated by Django 5.1.2 on 2025-11-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0003_rename_days_plan_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='availableSecond',
            field=models.IntegerField(default=3600),
        ),
    ]
