# Generated by Django 5.1.2 on 2025-11-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0004_plan_availablesecond'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
