# Generated by Django 5.1.2 on 2025-11-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0005_plan_features_plan_is_popular_plan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='error_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
