# Generated by Django 5.1.2 on 2025-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0006_payment_error_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
