# Generated by Django 4.2.16 on 2025-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('userType', models.CharField(blank=True, max_length=50)),
                ('activeStatus', models.BooleanField(default=True)),
                ('profile_image', models.CharField(blank=True, max_length=200)),
                ('dob', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('deviceType', models.CharField(blank=True, max_length=200)),
                ('accessToken', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('countryCode', models.CharField(blank=True, max_length=50)),
                ('accountStatus', models.BooleanField(default=True)),
                ('subscription', models.CharField(blank=True, default='trial', max_length=50)),
                ('lastLogin', models.DateTimeField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('countryCode', models.CharField(default='+91', max_length=10)),
                ('otp', models.CharField(max_length=5)),
                ('status', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
