# Generated by Django 5.1.2 on 2025-11-04 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='availableSecond',
            field=models.IntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='employee',
            name='endPlan',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='selectedPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subscription.plan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='startPlan',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
