# Generated by Django 5.1.2 on 2025-11-26 10:24

import Employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_employee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='endPlan',
            field=models.DateTimeField(default=Employee.models.default_end_plan),
        ),
    ]
