# Generated by Django 4.2.16 on 2025-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=200)),
                ('Password', models.CharField(blank=True, max_length=200)),
                ('Active', models.BooleanField(default=True)),
                ('Role', models.CharField(blank=True, max_length=100)),
                ('CreatedAt', models.DateField(auto_now_add=True)),
                ('UpdatedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
